# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170921_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
